mdl_core_home:
    path:     /
    defaults: { _controller: MDLCoreBundle:Main:home }

mdl_core_registration:
    path:     /registration
    defaults: { _controller: MDLCoreBundle:Main:registration }

mdl_core_payment:
    path:     /payment
    defaults: { _controller: MDLCoreBundle:Main:payment }

mdl_core_payment_checkout:
    path:     /payment/checkout
    defaults: { _controller: MDLCoreBundle:Main:paymentCheckout }

mdl_core_confirmation:
    path:     /confirmation
    defaults: { _controller: MDLCoreBundle:Main:confirmation }

